# Generated by Django 5.1.6 on 2025-02-18 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=100)),
                ('año_produccion', models.IntegerField()),
                ('fabricante', models.CharField(max_length=100)),
                ('longitud_total', models.FloatField()),
                ('longitud_cañon', models.FloatField()),
                ('peso', models.FloatField()),
                ('calibre', models.CharField(max_length=50)),
                ('capacidad_cargador', models.IntegerField()),
                ('velocidad_salida', models.FloatField()),
                ('eventos_historicos', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.categoria')),
            ],
        ),
    ]
